#!/bin/bash
#
# Copyright (c) 2018-2022 Markus Neifer
# Licensed under the MIT License.
# See file LICENSE in project root directory.
#

docker create \
  --tty \
  --interactive \
  --name fsharpsh \
  --mount type=bind,source=`pwd`/scripts,target=/scripts \
  fsharp:latest
