#!/bin/bash
#
# Copyright (c) 2018-2022 Markus Neifer
# Licensed under the MIT License.
# See file LICENSE in project root directory.
#

echo Attaching to F# shell container.
echo Use CTRL-p CTRL-q to detach.
echo "Use #quit to exit the interactive shell and destroy the container."

docker attach \
  fsharpsh
